networks:
  asvsp:
    name: asvsp
    external: true

services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8000:8080
      - 7077:7077
    env_file:
      - .env
    volumes:
      - ./sourceData:/home/sourceData
      - ./scripts:/home/scripts
    networks:
      - asvsp

  spark-worker:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8001:8081
    volumes:
      - ./sourceData:/home/sourceData
    env_file:
      - .env
    networks:
      - asvsp
